# -*- coding: utf-8 -*-
"""Chapter 3 - Exercise 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J06NkCM0VqAGcV81zkGJSq8evkvH6BkJ
"""

guest = ["Kanye", "Drake", "Yeat"]
print(guest[0], "you are invited to have dinner at my place.")
print(guest[1], "you are invited to have dinner at my place.")
print(guest[2], "you are invited to have dinner at my place.")

print("\nUnfortunately", guest[1], "can't make it to dinner.\n")
guest.insert(1,"Kid Cudi")

print(guest[0],"you are invited to have dinner at my place.")
print(guest[1], "you are invited to have dinner at my place.")
print(guest[2], "you are invited to have dinner at my place.")