# -*- coding: utf-8 -*-
"""Chapter 3 - Exercise 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOpOtZCKXoSbD19kKFlPPjdjccC_ysm_
"""

places = ["Tokyo", "America", "Canada", "Honolulu", "Jeddah"]

print("Original Order:", places)

print("\nAlphabetical Order:")
print(sorted(places))

print("\nOriginal Order:", places)

print("\nReversed Alphebetical Order:")
print(sorted(places, reverse=True))

print("\nReversed:")
places.reverse()
print(places)

print("\nOriginal Order:")
places.reverse()
print(places)

print("\nAlphabetical Order:")
places.sort()
print(places)

print("\n Reversed Alphabetical Order:")
places.sort(reverse=True)
print(places)