# -*- coding: utf-8 -*-
"""Chapter 3 - Exercise 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fEt56nxwlZVdsjxgQHZNrAcNqzK_OBDL
"""

guest = ["Kanye", "Drake", "Yeat"]
print(guest[0], "you are invited to have dinner at my place.")
print(guest[1], "you are invited to have dinner at my place.")
print(guest[2], "you are invited to have dinner at my place.")