# -*- coding: utf-8 -*-
"""Chapter 3 - Exercise 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmVfZ1PQ4Wb25mQ2SWdj1U2XEubeAdk_
"""

names = ["Juan", "Ken", "Joshua"]

print(names[0])

print(names[1])

print(names[2])