# -*- coding: utf-8 -*-
"""Chapter 3 - Exercise 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhsUvnZr3BLA5F46afFR3LMfCCdHFzzD
"""

transport = ["Car", "Bus", "Aeroplane", "Boat", "Motorcycle"]

print("I would like to ride in a",transport[0])

print("My dad wants to drive a",transport[1])

print("My brother wants to be a pilot in an",transport[2])

print("I would like to own a",transport[3])

print("My sister wants to learn how to drive a",transport[4])