# -*- coding: utf-8 -*-
"""Chapter 3 - Exercise 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14OtHZiyl4rS2iJ8sd-6odvXtXEtzrqMz
"""

guest = ["Kanye", "Drake", "Yeat"]
print(guest[0], "you are invited to have dinner at my place.")
print(guest[1], "you are invited to have dinner at my place.")
print(guest[2], "you are invited to have dinner at my place.")

print("\nUnfortunately", guest[1], "can't make it to dinner.\n")
guest.insert(1,"Kid Cudi")

print(guest[0],"you are invited to have dinner at my place.")
print(guest[1], "you are invited to have dinner at my place.")
print(guest[2], "you are invited to have dinner at my place.")

guest.pop(2)
print("\nSorry",guest[2],"we don't have space for you at the table.")
guest.pop(0)
print("Sorry",guest[0],"we don't have space for you at the table.")

print("\n",guest[0],"you are still invited to have dinner at my place.")
print(guest[1], "you are still invited to have dinner at my place.")

del(guest[0:2])
print(guest)