# -*- coding: utf-8 -*-
"""Chapter 3 - Exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YnhDyNpzyCWJbcyYncpRvyBCj383HHAu
"""

names = ["Juan", "Ken", "Joshua"]

print(names[0], "is my friend.")

print(names[1], "is my friend.")

print(names[2], "is my friend.")