# -*- coding: utf-8 -*-
"""Chapter 2 - Exercise 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbExXCjACxLDhSEOfHtbPtGeICH62jZO
"""

money = 50
usb = int(money / 6)
print("You can get", usb, "usbs")
change = int(money % 6)
print ("and your change will be", change, "pounds")