# -*- coding: utf-8 -*-
"""Chapter 2 - Exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18c5k8rq7GYYbWPzNpAiQluJfSw99KvNZ
"""

print ("Nelson Mandela once said, \"The greatest glory in living lies not in never falling, but in rising every time we fall.\"")