# -*- coding: utf-8 -*-
"""Chapter 2 - Exercise 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/146JAm5ojiX2SW-cF8DNd9KWmW-oKcHiR
"""

favenumber = 17
print ("My favourite number is", favenumber)