# -*- coding: utf-8 -*-
"""Chapter 2 - Exercise 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ows2CXy8sK6iq-K0aDuI_ZjFJqWpyl5q
"""

message = "Hello World!"
print (message)
message = "Hello Earth!"
print (message)