# -*- coding: utf-8 -*-
"""Chapter 2 - Exercise 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNxkhB6DYfti1H5TmF9iFe_Nb0RrC7oh
"""

name = " \tJonathan\n "

print (name)
print (name.lstrip())
print (name.rstrip())
print (name.strip())