# -*- coding: utf-8 -*-
"""Chapter 1 - Exercise 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JP9nNbX4rPRxoMU9lICHzU_3H-DW93Xe

Exercise 3: Print date and Time ☑️
"""

import datetime

now = datetime.datetime.now()
print("Current time is: ")
print(now.strftime("%d-%m-%y %H-%M-%S"))