# -*- coding: utf-8 -*-
"""Chapter 1 - Exercise 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PqEX3pbT8m5Y2zIl7kSL8KUScXF2hGD8

Exercise 4: Strings Concatination ☑️
"""

color = "red"
animal = "dog"
name = "johnny"
print(color, animal, name)