# -*- coding: utf-8 -*-
"""Chapter 1 - Exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5afp6ehPJi4BQznTZvYn1ZCUqMXWnc1

Exercise 2: Print the Version of Python ☑️
"""

!python --version