# -*- coding: utf-8 -*-
"""Chapter 1 - Exercise 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGHJSPF6DFHGSbF6E9bRQWYI4vbG1FDb
"""

print ("Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How I \nwonder what you are")