# -*- coding: utf-8 -*-
"""Chapter 1 - Exercise 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yPgGbmKiW1C5YpGYVLqJV6kr8pGqyGBl

Exercise 5: Compute area of Circle ☑️
"""

radius = int(input("Radius of circle: "))
area = 3.14 * radius ** 2
print (area)